apiVersion: v1
kind: Service
metadata:
  name: bitbucket-ssh
  namespace: bitbucket
  labels:
    app: bitbucket
spec:
  type: ClusterIP
  selector:
    app: bitbucket
  ports:
    - name: ssh
      protocol: TCP
      port: 7999
      nodePort: 30022
      targetPort: 7999
