apiVersion: v1
kind: Service
metadata:
  name: bitbucket-http
  namespace: bitbucket
  labels:
    app: bitbucket
spec:
  type: ClusterIP
  selector:
    app: bitbucket
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7990
