apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket
  namespace: bitbucket
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
