kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-user
  namespace: bitbucket
subjects:
  - kind: ServiceAccount
    name: elasticsearch
  - kind: ServiceAccount
    name: bitbucket
roleRef:
  kind: Role
  name: elasticsearch-user
  apiGroup: rbac.authorization.k8s.io
