kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-user
  namespace: bitbucket
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
    resourceNames: ["elasticsearch"]
