apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  namespace: bitbucket
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  resources:
    requests:
      storage: 8Gi
