apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: bitbucket
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
